[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Jon Chambers <jon.chambers@gmail.com>"]
edition = "2018"

[[bin]]
name = "day01"

[[bin]]
name = "day02"

[[bin]]
name = "day03"

[dependencies]
simple-error = "0.2.2"
