[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Jon Chambers <jon.chambers@gmail.com>"]
edition = "2018"

[[bin]]
name = "day01"

[[bin]]
name = "day02"

[[bin]]
name = "day03"

[[bin]]
name = "day04"

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
simple-error = "0.2.2"
